main = "worker.js"

name = "tg-linversehelperbot"

compatibility_date = "2026-07-14"

[[kv_namespaces]]
binding = "DATA_KV"
id = "6aea0c9c274c4a628ccfeb165e2853f0"

[[d1_databases]]
binding = "DATA_DB"
database_name = "tg-linbot"
database_id = "f894bcee-a08f-488c-b157-3e63465e8553"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
